build:
  image: node:4
  commands:
    - npm install --silent
    - npm run lint
deploy:
  ssh:
    host: 0u0.moe
    user: nya
    port: 22
    commands:
      - cd /srv/http/Blipay
      - git pull
      - npm install
      - npm run build
      - pm2 start pm2.production.json
