build:
  image: node:4
  commands:
    - npm install --silent
    - npm run lint
    - npm run test
compose:
  database:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=blipay
      - MYSQL_USER=blipay
      - MYSQL_PASSWORD=blipay
deploy:
  ssh:
    host: 0u0.moe
    user: nya
    port: 22
    commands:
      - . ~/.nvm/nvm.sh
      - cd /srv/http/Blipay
      - git pull
      - npm install
      - npm run build
      - pm2 start pm2.production.json
